In [1]:
import pandas as pd

In [2]:
excel_file_path = 'C:/Users/ASUS/OneDrive/Documents/實習/Rebas/CPBL_2023.xlsx'

## 計算個人殘壘數

In [3]:
sheet_name1 = 'AWAY-打席資訊'  
sheet_name2 = 'HOME-打席資訊'

In [4]:
away = pd.read_excel(excel_file_path, sheet_name=sheet_name1)
home = pd.read_excel(excel_file_path, sheet_name=sheet_name2)

In [5]:
cols = ['打者','壘包狀態','開始出局數','結束出局數']

In [6]:
away_lob = away[cols]
home_lob = home[cols]

In [7]:
LOB = pd.concat([home_lob,away_lob], ignore_index=False)

In [8]:
LOB['出局數']=LOB['結束出局數']-LOB['開始出局數']

In [9]:
LOB = LOB[LOB['出局數'] != 0]
LOB.loc[LOB['出局數'] == 2, '出局數'] = 1

In [10]:
def classify_lob(row):
    if row['壘包狀態'] in [1,2,4]:
        return 1
    elif row['壘包狀態'] in [3,5,6]:
        return 2
    elif row['壘包狀態'] in [7]:
        return 3
    else:
        return 0


LOB['LOB'] = LOB.apply(classify_lob, axis=1)

LOB

        打者  壘包狀態  開始出局數  結束出局數  出局數  LOB
0      陳傑憲     0      0      1    1    0
1      林靖凱     0      1      2    1    0
2      蘇智傑     0      2      3    1    0
4      林安可     1      0      1    1    1
5      胡金龍     2      1      2    1    1
...    ...   ...    ...    ...  ...  ...
11752  朱育賢     0      1      2    1    0
11753  郭嚴文     0      2      3    1    0
11754  梁家榮     0      0      1    1    0
11755  宋嘉翔     0      1      2    1    0
11756  林承飛     0      2      3    1    0

[15380 rows x 6 columns]

In [11]:
LOB= LOB.groupby(['打者']).agg({'LOB':'sum'})
LOB

     LOB
打者
于森旭   19
何恆佑   20
余德龍   35
全浩瑋    0
冉承霖   14
..   ...
高孝儀   56
高宇杰  133
黃勇傳   50
黃鈞聲    6
黃韋盛   50

[148 rows x 1 columns]

## 球員個人成績整理

In [12]:
sheet_name3 = 'AWAY-BOX-打擊'  
sheet_name4 = 'HOME-BOX-打擊'

In [13]:
away = pd.read_excel(excel_file_path, sheet_name=sheet_name3)
home = pd.read_excel(excel_file_path, sheet_name=sheet_name4)

In [14]:
merged_stat = pd.concat([away, home], ignore_index=True)
merged_stat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6975 entries, 0 to 6974
Data columns (total 28 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   比賽編號    6975 non-null   int64
 1   比賽日期    6975 non-null   object
 2   球場      6975 non-null   object
 3   客場      6975 non-null   object
 4   主場      6975 non-null   object
 5   打序      6975 non-null   int64
 6   背號      6975 non-null   int64
 7   名稱      6975 non-null   object
 8   打席      6975 non-null   int64
 9   打數      6975 non-null   int64
 10  得分      6975 non-null   int64
 11  安打      6975 non-null   int64
 12  打點      6975 non-null   int64
 13  二安      6975 non-null   int64
 14  三安      6975 non-null   int64
 15  全壘打     6975 non-null   int64
 16  滾地雙殺    6975 non-null   int64
 17  雙殺      6975 non-null   int64
 18  三殺      6975 non-null   int64
 19  四壞      6975 non-null   int64
 20  故意四壞    6975 non-null   int64
 21  觸身      6975 non-null   int64
 22  三振      6975 non-null   int64
 23  犧短      6975 non-null   int64
 24  犧飛      6975 non-null   int64
 25  失誤上壘    6975 non-null   int64
 26  盜壘      6975 non-null   int64
 27  盜壘失敗    6975 non-null   int64
dtypes: int64(23), object(5)
memory usage: 1.5+ MB

In [15]:
merged_stat = merged_stat.drop(['球場',"比賽編號","比賽日期","客場","主場","打序","背號",'滾地雙殺','雙殺','三殺','失誤上壘','故意四壞','犧短','犧飛'], axis = 1)
merged_stat

       名稱  打席  打數  得分  安打  打點  二安  三安  全壘打  四壞  觸身  三振  盜壘  盜壘失敗
0     董子恩   5   5   0   2   1   0   0    0   0   0   0   0     0
1     王念好   5   5   0   3   2   0   0    0   0   0   1   0     0
2     池恩齊   0   0   0   0   0   0   0    0   0   0   0   0     0
3      陳真   5   4   0   1   0   0   0    0   1   0   1   0     0
4     高國麟   2   1   0   0   0   0   0    0   1   0   0   0     0
...   ...  ..  ..  ..  ..  ..  ..  ..  ...  ..  ..  ..  ..   ...
6970  張志豪   3   3   0   0   0   0   0    0   0   0   1   0     0
6971  曾頌恩   1   1   0   0   0   0   0    0   0   0   0   0     0
6972  福來喜   3   3   0   0   0   0   0    0   0   0   2   0     0
6973  高宇杰   1   1   0   0   0   0   0    0   0   0   0   0     0
6974  岳東華   4   3   1   1   0   0   0    0   1   0   1   0     0

[6975 rows x 14 columns]

In [16]:
agg_dict = {
    "打席": "sum",
    "打數": "sum",
    "得分": "sum",
    "安打": "sum",
    "打點": "sum",
    "二安": "sum",
    "三安": "sum",
    "全壘打": "sum",
    "四壞": "sum",
    "觸身": "sum",
    "三振": "sum",
    "盜壘": "sum",
    "盜壘失敗": "sum"
}
batter_total = merged_stat.groupby("名稱").agg(agg_dict).reset_index()
batter_total

      名稱   打席   打數  得分  安打  打點  二安  三安  全壘打  四壞  觸身  三振  盜壘  盜壘失敗
0    于森旭   38   38   2   6   1   1   0    0   0   0   9   4     0
1    何恆佑   47   45   4   8   0   2   0    0   1   0  12   0     0
2    余德龍   52   48   5  10   5   1   0    1   1   0  12   0     1
3    全浩瑋    5    5   0   1   0   0   0    0   0   0   1   0     0
4    冉承霖   32   29   4   7   3   0   0    0   3   0  12   0     0
..   ...  ...  ...  ..  ..  ..  ..  ..  ...  ..  ..  ..  ..   ...
145  高宇杰  231  212  14  40  10   4   0    1  14   0  54   1     0
146  黃勇傳  121  107  12  25   9   3   0    0  11   2  19   2     2
147  黃鈞聲   10   10   0   3   0   0   0    0   0   0   4   0     0
148  黃鈞麟    1    0   0   0   0   0   0    0   0   1   0   0     0
149  黃韋盛   88   80  14  18   5   2   0    0   6   0  25   0     0

[150 rows x 14 columns]

In [17]:
batter_total['一安'] = batter_total['安打']-batter_total['二安']-batter_total['三安']-batter_total['全壘打']
batter_total['TB'] = batter_total['一安']+batter_total['二安']*2+batter_total['三安']*3+batter_total['全壘打']*4

## 殘壘數和個人成績資料合併

In [18]:
batter_total = batter_total.rename(columns={'名稱':'打者'})

In [19]:
df = pd.merge(batter_total, LOB, on=['打者'])

In [20]:
df

      打者   打席   打數  得分  安打  打點  二安  三安  全壘打  四壞  觸身  三振  盜壘  盜壘失敗  一安  TB  LOB
0    于森旭   38   38   2   6   1   1   0    0   0   0   9   4     0   5   7   19
1    何恆佑   47   45   4   8   0   2   0    0   1   0  12   0     0   6  10   20
2    余德龍   52   48   5  10   5   1   0    1   1   0  12   0     1   8  14   35
3    全浩瑋    5    5   0   1   0   0   0    0   0   0   1   0     0   1   1    0
4    冉承霖   32   29   4   7   3   0   0    0   3   0  12   0     0   7   7   14
..   ...  ...  ...  ..  ..  ..  ..  ..  ...  ..  ..  ..  ..   ...  ..  ..  ...
143  高孝儀  144  124  11  29   9   4   1    0  12   3  21   2     2  24  35   56
144  高宇杰  231  212  14  40  10   4   0    1  14   0  54   1     0  35  47  133
145  黃勇傳  121  107  12  25   9   3   0    0  11   2  19   2     2  22  28   50
146  黃鈞聲   10   10   0   3   0   0   0    0   0   0   4   0     0   3   3    6
147  黃韋盛   88   80  14  18   5   2   0    0   6   0  25   0     0  16  20   50

[148 rows x 17 columns]

## 係數整理+計算ABR(來自計算WAR時的RE24 四捨五入至小數點第三位)

## 原公式:ABR = (0.47)x1B + (0.78)x2B + (1.09)x3B + (1.40)xHR + (0.33)x(BB+HBP) - (0.25)x(AB-H) - (0.50)x(H+BB+HBP-LOB-R-CS)

## 2023 RE整理
### 一安 0.489
### 二安 0.804
### 三安 1.072
### HR 1.712
### BB 0.354
### HBP 0.373
#### 係數"0.25"和"0.5" 尚未做變動 需要另外處理 EX:0.25由來可能是計算打擊率和得分的關係得來

In [21]:
df['ABR(2023RE)']=0.489*df['一安']+0.804*df['二安']+1.072*df['三安']+1.712*df['全壘打']+0.354*df['四壞']+0.373*df['觸身']-0.25*(df['打數']-df['安打'])-0.5*(df['安打']+df['四壞']+df['觸身']-df['LOB']-df['得分']-df['盜壘失敗'])

## 2020~2023 RE整理
### 一安 0.503
### 二安 0.807
### 三安 1.124
### HR 1.718
### BB 0.360
### HBP 0.379
#### 係數"0.25"和"0.5" 尚未做變動 需要另外處理

In [22]:
df['ABR(2020~2023RE)']=0.503*df['一安']+0.807*df['二安']+1.124*df['三安']+1.718*df['全壘打']+0.360*df['四壞']+0.379*df['觸身']-0.25*(df['打數']-df['安打'])-0.5*(df['安打']+df['四壞']+df['觸身']-df['LOB']-df['得分']-df['盜壘失敗'])

In [23]:
df

,打者,打席,打數,得分,安打,打點,二安,三安,全壘打,四壞,觸身,三振,盜壘,盜壘失敗,一安,TB,LOB,ABR(2023RE),ABR(2020~2023RE)
0,于森旭,38,38,2,6,1,1,0,0,0,0,9,4,0,5,7,19,2.749,2.822
1,何恆佑,47,45,4,8,0,2,0,0,1,0,12,0,0,6,10,20,3.146,3.242
2,余德龍,52,48,5,10,5,1,0,1,1,0,12,0,1,8,14,35,12.282,12.409
3,全浩瑋,5,5,0,1,0,0,0,0,0,0,1,0,0,1,1,0,-1.011,-0.997
4,冉承霖,32,29,4,7,3,0,0,0,3,0,12,0,0,7,7,14,2.985,3.101
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
143,高孝儀,144,124,11,29,9,4,1,0,12,3,21,2,2,24,35,56,10.141,10.631
144,高宇杰,231,212,14,40,10,4,0,1,14,0,54,1,0,35,47,133,30.499,31.091
145,黃勇傳,121,107,12,25,9,3,0,0,11,2,19,2,2,22,28,50,10.310,10.705
146,黃鈞聲,10,10,0,3,0,0,0,0,0,0,4,0,0,3,3,6,1.217,1.259
147,黃韋盛,88,80,14,18,5,2,0,0,6,0,25,0,0,16,20,50,16.056,16.322

In [25]:
#df.to_excel('2023ABR.xlsx', index=True)